/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.3.72"

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {

    val versionKtor = "1.3.0"
    val versionExposed = "0.26.1"
    val versionLog4j = "2.13.3"

    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    // Ktor
    implementation("io.ktor", "ktor-server-core", versionKtor)
    implementation("io.ktor", "ktor-server-netty", versionKtor)
    implementation("io.ktor", "ktor-jackson", versionKtor)
    implementation("io.ktor", "ktor-auth-jwt", versionKtor)

    // Exposed (DB)
    implementation("org.jetbrains.exposed", "exposed-core", versionExposed)
    implementation("org.jetbrains.exposed", "exposed-jdbc", versionExposed)

    // PostreSql + DB configuration
    implementation("org.postgresql", "postgresql", "42.2.12")
    implementation("org.apache.cassandra", "cassandra-all", "0.8.1")
    implementation("com.zaxxer", "HikariCP", "3.2.0")

    // Logging
    implementation("org.apache.logging.log4j", "log4j-api", versionLog4j)
    implementation("org.apache.logging.log4j", "log4j-core", versionLog4j)

}

application {
    // Define the main class for the application.
    mainClassName = "WorkTracker.AppKt"
}
