/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.3.72"

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {

    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    // Ktor
    implementation("io.ktor:ktor-server-core:1.3.0")
    implementation("io.ktor:ktor-server-netty:1.3.0")
    implementation("io.ktor:ktor-jackson:1.3.0")

    // Exposed (DB)
    compile("org.jetbrains.exposed", "exposed-core", "0.24.1")
    compile("org.jetbrains.exposed", "exposed-jdbc", "0.24.1")

    // PostreSql + DB configuration
    compile("org.postgresql:postgresql:42.2.2")
    compile("com.zaxxer:HikariCP:3.2.0")
    compile("org.apache.cassandra:cassandra-all:0.8.1")
    compile("org.apache.logging.log4j:log4j-api:2.13.3")
    compile("org.apache.logging.log4j:log4j-core:2.13.3")

}

application {
    // Define the main class for the application.
    mainClassName = "WorkTracker.AppKt"
}
